[package]
name = "kafka-rust-playg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9.0"
serde = "1.0"
thiserror = "1.0"